"""
Validate Python construct_matrixQ implementation against MATLAB reference data.

This script loads reference data generated by MATLAB's construct_matrixQ function
and validates that the Python implementation produces equivalent results.
"""

import numpy as np
import sys
import os
from scipy.io import loadmat

sys.path.append(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
from utils.construct_matrixQ import construct_matrixQ


class MATLABReferenceValidator:
    """Validator for Python construct_matrixQ against MATLAB reference implementation."""

    def __init__(self, matlab_data_path=None):
        """
        Initialize validator with MATLAB reference data.

        Args:
            matlab_data_path: Path to MATLAB reference data file.
                            If None, will look for default location.
        """
        if matlab_data_path is None:
            # Default path relative to this script
            script_dir = os.path.dirname(os.path.abspath(__file__))
            project_root = os.path.dirname(os.path.dirname(os.path.dirname(script_dir)))
            matlab_data_path = os.path.join(
                project_root, 'OBS_for_CRLB_ISAC', 'tests', 'test_construct_matrixQ_data.mat'
            )

        self.matlab_data_path = matlab_data_path
        self.load_matlab_reference_data()

    def load_matlab_reference_data(self):
        """Load MATLAB reference data from .mat file."""
        try:
            print(f"Loading MATLAB reference data from: {self.matlab_data_path}")
            mat_data = loadmat(self.matlab_data_path)

            # Extract test data structure
            self.test_data = mat_data['test_data'][0, 0]

            # Store all test cases
            self.test_cases = {}
            for i in range(1, 4):  # We have 3 test cases
                test_case = f'test{i}'
                self.test_cases[test_case] = {
                    'inputs': {
                        'L': float(self.test_data[test_case][0, 0]['inputs'][0, 0]['L'][0, 0]),
                        'noise_s': float(self.test_data[test_case][0, 0]['inputs'][0, 0]['noise_s'][0, 0]),
                        'Phi': self.test_data[test_case][0, 0]['inputs'][0, 0]['Phi'],
                        'A': self.test_data[test_case][0, 0]['inputs'][0, 0]['A'],
                        'dAtheta': self.test_data[test_case][0, 0]['inputs'][0, 0]['dAtheta'],
                        'dAphi': self.test_data[test_case][0, 0]['inputs'][0, 0]['dAphi'],
                        'B': self.test_data[test_case][0, 0]['inputs'][0, 0]['B'],
                        'dBtheta': self.test_data[test_case][0, 0]['inputs'][0, 0]['dBtheta'],
                        'dBphi': self.test_data[test_case][0, 0]['inputs'][0, 0]['dBphi'],
                        'U': self.test_data[test_case][0, 0]['inputs'][0, 0]['U']
                    },
                    'output': self.test_data[test_case][0, 0]['output']
                }

            print("✓ Successfully loaded MATLAB reference data")
            print(f"  Number of test cases: {len(self.test_cases)}")

        except Exception as e:
            raise RuntimeError(f"Failed to load MATLAB reference data: {e}")

    def validate_test_case(self, test_case):
        """Validate Python construct_matrixQ for a single test case."""
        print(f"\n=== Validating {test_case} ===")

        inputs = self.test_cases[test_case]['inputs']
        matlab_output = self.test_cases[test_case]['output']

        # Run Python implementation
        import time
        start_time = time.perf_counter()
        python_output = construct_matrixQ(
            inputs['L'], inputs['noise_s'], inputs['Phi'],
            inputs['A'], inputs['dAtheta'], inputs['dAphi'],
            inputs['B'], inputs['dBtheta'], inputs['dBphi'],
            inputs['U']
        )
        python_time = time.perf_counter() - start_time

        # Compare results
        abs_diff = np.abs(python_output - matlab_output)
        rel_diff = abs_diff / (np.abs(matlab_output) + np.finfo(float).eps)

        max_abs_diff = np.max(abs_diff)
        max_rel_diff = np.max(rel_diff)
        mean_abs_diff = np.mean(abs_diff)
        mean_rel_diff = np.mean(rel_diff)

        print(f"Dimensions: Python{python_output.shape} vs MATLAB{matlab_output.shape}")
        print(f"Maximum absolute difference: {max_abs_diff:.2e}")
        print(f"Maximum relative difference: {max_rel_diff:.2e}")
        print(f"Mean absolute difference: {mean_abs_diff:.2e}")
        print(f"Mean relative difference: {mean_rel_diff:.2e}")

        # Tolerance assessment
        abs_tol = 1e-6  # Relaxed for multiple matrix multiplications
        rel_tol = 1e-8
        
        print(f"\nTolerance Assessment:")
        print(f"  Absolute tolerance: {abs_tol:.1e} -> {'PASS' if max_abs_diff < abs_tol else 'FAIL'}")
        print(f"  Relative tolerance: {rel_tol:.1e} -> {'PASS' if max_rel_diff < rel_tol else 'FAIL'}")
        
        # Machine precision check
        if max_abs_diff < 1e-12:
            print(f"  ✓ Differences are at machine precision level")
            validation_passed = True
        elif max_abs_diff < abs_tol and max_rel_diff < rel_tol:
            print(f"  ✓ Differences are within acceptable tolerance")
            validation_passed = True
        else:
            print(f"  ✗ Differences exceed acceptable tolerance")
            validation_passed = False

        return validation_passed, {
            'max_abs_diff': max_abs_diff,
            'max_rel_diff': max_rel_diff,
            'mean_abs_diff': mean_abs_diff,
            'mean_rel_diff': mean_rel_diff,
            'python_time': python_time,
            'Q_python': python_output,
            'Q_matlab': matlab_output
        }

    def validate_all_test_cases(self):
        """Validate all test cases."""
        all_results = {}
        all_passed = True

        for test_case in self.test_cases:
            passed, results = self.validate_test_case(test_case)
            all_results[test_case] = results
            all_passed &= passed

        return all_passed, all_results

    def test_mathematical_properties(self, test_case):
        """Test mathematical properties of the Q matrix."""
        print(f"\n=== MATHEMATICAL PROPERTIES for {test_case} ===")

        inputs = self.test_cases[test_case]['inputs']
        Q_python = construct_matrixQ(
            inputs['L'], inputs['noise_s'], inputs['Phi'],
            inputs['A'], inputs['dAtheta'], inputs['dAphi'],
            inputs['B'], inputs['dBtheta'], inputs['dBphi'],
            inputs['U']
        )
        Q_matlab = self.test_cases[test_case]['output']

        # Test scaling with L
        Q_2L = construct_matrixQ(
            2*inputs['L'], inputs['noise_s'], inputs['Phi'],
            inputs['A'], inputs['dAtheta'], inputs['dAphi'],
            inputs['B'], inputs['dBtheta'], inputs['dBphi'],
            inputs['U']
        )
        scale_L_error = np.max(np.abs(Q_2L - 2*Q_python))
        print(f"L scaling property: {'✓' if scale_L_error < 1e-12 else '✗'} (error: {scale_L_error:.2e})")

        # Test scaling with noise
        Q_2noise = construct_matrixQ(
            inputs['L'], 2*inputs['noise_s'], inputs['Phi'],
            inputs['A'], inputs['dAtheta'], inputs['dAphi'],
            inputs['B'], inputs['dBtheta'], inputs['dBphi'],
            inputs['U']
        )
        scale_noise_error = np.max(np.abs(Q_2noise - 0.5*Q_python))
        print(f"Noise scaling property: {'✓' if scale_noise_error < 1e-12 else '✗'} (error: {scale_noise_error:.2e})")

        # Test matrix properties
        is_square = Q_python.shape[0] == Q_python.shape[1]
        print(f"Square matrix: {'✓' if is_square else '✗'}")

        if is_square:
            # Test for symmetry/Hermitian property
            is_hermitian = np.allclose(Q_python, Q_python.conj().T)
            print(f"Hermitian matrix: {'✓' if is_hermitian else '✗'}")


def main():
    """Run the complete validation suite."""
    print("=== PYTHON construct_matrixQ VALIDATION AGAINST MATLAB REFERENCE ===\n")

    try:
        # Initialize validator
        validator = MATLABReferenceValidator()

        # Run validation for all test cases
        passed, results = validator.validate_all_test_cases()

        # Test mathematical properties for each test case
        for test_case in validator.test_cases:
            validator.test_mathematical_properties(test_case)

        # Final summary
        print(f"\n=== VALIDATION SUMMARY ===")
        if passed:
            print("🎉 VALIDATION PASSED: Python implementation matches MATLAB reference!")
            print(f"   Maximum difference across all tests: {max(r['max_abs_diff'] for r in results.values()):.2e}")
        else:
            print("❌ VALIDATION FAILED: Python implementation differs from MATLAB reference")
            print(f"   Maximum difference across all tests: {max(r['max_abs_diff'] for r in results.values()):.2e}")

        return passed

    except Exception as e:
        print(f"❌ Validation failed with error: {e}")
        return False


if __name__ == "__main__":
    success = main()
    sys.exit(0 if success else 1)
