"""
Validate Python calculateFIM implementation against MATLAB reference data.

This script loads reference data generated by MATLAB's calculateFIM function
and validates that the Python implementation produces equivalent results.
"""

import numpy as np
import sys
import os
from scipy.io import loadmat

sys.path.append(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
from utils.calculate_fim import calculate_fim, calculateFIM


class MATLABReferenceValidator:
    """Validator for Python calculateFIM against MATLAB reference implementation."""

    def __init__(self, matlab_data_path=None):
        """
        Initialize validator with MATLAB reference data.
        
        Args:
            matlab_data_path: Path to MATLAB reference data file.
                            If None, will look for default location.
        """
        if matlab_data_path is None:
            # Default path relative to this script
            script_dir = os.path.dirname(os.path.abspath(__file__))
            project_root = os.path.dirname(os.path.dirname(os.path.dirname(script_dir)))
            matlab_data_path = os.path.join(
                project_root, 'OBS_for_CRLB_ISAC', 'tests', 'test_calculate_fim_data.mat'
            )
        
        self.matlab_data_path = matlab_data_path
        self.load_matlab_reference_data()

    def load_matlab_reference_data(self):
        """Load MATLAB reference data from .mat file."""
        try:
            print(f"Loading MATLAB reference data from: {self.matlab_data_path}")
            mat_data = loadmat(self.matlab_data_path)
            
            # Extract the nested structure
            if 'matlab_reference_data' in mat_data:
                ref_data = mat_data['matlab_reference_data'][0, 0]  # Extract from object array
            else:
                ref_data = mat_data
            
            # Extract all parameters
            self.L = float(ref_data['L'][0, 0])
            self.noise_s = float(ref_data['noise_s'][0, 0])
            self.W = ref_data['W']
            self.A = ref_data['A']
            self.dAtheta = ref_data['dAtheta']
            self.dAphi = ref_data['dAphi']
            self.B = ref_data['B']
            self.dBtheta = ref_data['dBtheta']
            self.dBphi = ref_data['dBphi']
            self.U = ref_data['U']
            self.FIM_matlab_reference = ref_data['FIM_matlab_reference']
            
            # Optional metadata
            self.M = int(ref_data['M'][0, 0])
            self.matlab_time = float(ref_data['matlab_computation_time'][0, 0])
            self.matlab_cond_num = float(ref_data['matlab_condition_number'][0, 0])
            
            print("✓ Successfully loaded MATLAB reference data")
            print(f"  Test parameters: L={self.L}, noise_s={self.noise_s}, M={self.M}")
            print(f"  Matrix dimensions: W{self.W.shape}, FIM{self.FIM_matlab_reference.shape}")
            print(f"  MATLAB computation time: {self.matlab_time:.6f} seconds")
            
        except Exception as e:
            raise RuntimeError(f"Failed to load MATLAB reference data: {e}")

    def validate_python_implementation(self):
        """Validate Python calculateFIM against MATLAB reference."""
        print("\n=== PYTHON VALIDATION AGAINST MATLAB REFERENCE ===")
        
        # Test both function versions
        print("\nTesting calculate_fim function...")
        import time
        start_time = time.perf_counter()
        FIM_python_new = calculate_fim(self.L, self.noise_s, self.W, self.A, 
                                      self.dAtheta, self.dAphi, self.B, 
                                      self.dBtheta, self.dBphi, self.U)
        python_time_new = time.perf_counter() - start_time
        
        print("Testing calculateFIM function (legacy)...")
        start_time = time.perf_counter()
        FIM_python_legacy = calculateFIM(self.L, self.noise_s, self.W, self.A,
                                        self.dAtheta, self.dAphi, self.B,
                                        self.dBtheta, self.dBphi, self.U)
        python_time_legacy = time.perf_counter() - start_time
        
        print(f"Python computation times:")
        print(f"  calculate_fim: {python_time_new:.6f} seconds")
        print(f"  calculateFIM:  {python_time_legacy:.6f} seconds")
        print(f"  MATLAB time:   {self.matlab_time:.6f} seconds")
        
        # Verify both Python functions are identical
        func_diff = np.max(np.abs(FIM_python_new - FIM_python_legacy))
        if func_diff < 1e-15:
            print("✓ Both Python functions produce identical results")
        else:
            print(f"✗ Python functions differ (max diff: {func_diff:.2e})")
            
        # Main validation: Python vs MATLAB
        print(f"\n=== PYTHON vs MATLAB COMPARISON ===")
        
        abs_diff = np.abs(FIM_python_new - self.FIM_matlab_reference)
        rel_diff = abs_diff / (np.abs(self.FIM_matlab_reference) + np.finfo(float).eps)
        
        max_abs_diff = np.max(abs_diff)
        max_rel_diff = np.max(rel_diff)
        mean_abs_diff = np.mean(abs_diff)
        mean_rel_diff = np.mean(rel_diff)
        
        print(f"Dimensions: Python{FIM_python_new.shape} vs MATLAB{self.FIM_matlab_reference.shape}")
        print(f"Maximum absolute difference: {max_abs_diff:.2e}")
        print(f"Maximum relative difference: {max_rel_diff:.2e}")
        print(f"Mean absolute difference: {mean_abs_diff:.2e}")
        print(f"Mean relative difference: {mean_rel_diff:.2e}")
        
        # Tolerance assessment
        abs_tol = 1e-10
        rel_tol = 1e-8
        
        print(f"\nTolerance Assessment:")
        print(f"  Absolute tolerance: {abs_tol:.1e} -> {'PASS' if max_abs_diff < abs_tol else 'FAIL'}")
        print(f"  Relative tolerance: {rel_tol:.1e} -> {'PASS' if max_rel_diff < rel_tol else 'FAIL'}")
        
        # Machine precision check
        if max_abs_diff < 1e-12:
            print(f"  ✓ Differences are at machine precision level")
            validation_passed = True
        elif max_abs_diff < abs_tol:
            print(f"  ✓ Differences are within acceptable tolerance")
            validation_passed = True
        else:
            print(f"  ✗ Differences exceed acceptable tolerance")
            validation_passed = False

        # Mathematical property validation
        print(f"\n=== MATHEMATICAL PROPERTIES ===")
        
        # Hermitian property
        python_hermitian = np.allclose(FIM_python_new, FIM_python_new.conj().T)
        matlab_hermitian = np.allclose(self.FIM_matlab_reference, self.FIM_matlab_reference.conj().T)
        print(f"Hermitian: Python {'✓' if python_hermitian else '✗'}, MATLAB {'✓' if matlab_hermitian else '✗'}")
        
        # Positive semi-definite
        python_eigs = np.linalg.eigvals(FIM_python_new)
        matlab_eigs = np.linalg.eigvals(self.FIM_matlab_reference)
        python_psd = np.all(np.real(python_eigs) >= -1e-10)
        matlab_psd = np.all(np.real(matlab_eigs) >= -1e-10)
        print(f"Positive semi-definite: Python {'✓' if python_psd else '✗'}, MATLAB {'✓' if matlab_psd else '✗'}")
        
        # Condition numbers
        python_cond = np.linalg.cond(FIM_python_new)
        matlab_cond = self.matlab_cond_num
        cond_diff = abs(python_cond - matlab_cond) / matlab_cond
        print(f"Condition numbers: Python {python_cond:.2e}, MATLAB {matlab_cond:.2e} (diff: {cond_diff:.2e})")
        
        return validation_passed, {
            'max_abs_diff': max_abs_diff,
            'max_rel_diff': max_rel_diff,
            'mean_abs_diff': mean_abs_diff,
            'mean_rel_diff': mean_rel_diff,
            'python_time': python_time_new,
            'matlab_time': self.matlab_time,
            'python_cond': python_cond,
            'matlab_cond': matlab_cond,
            'FIM_python': FIM_python_new,
            'FIM_matlab': self.FIM_matlab_reference
        }

    def test_input_variations(self):
        """Test various input scenarios."""
        print(f"\n=== INPUT VARIATION TESTS ===")
        
        # Test with covariance matrix input
        Rx = self.W @ self.W.conj().T
        FIM_Rx = calculate_fim(self.L, self.noise_s, Rx, self.A, self.dAtheta, self.dAphi,
                              self.B, self.dBtheta, self.dBphi, self.U)
        FIM_W = calculate_fim(self.L, self.noise_s, self.W, self.A, self.dAtheta, self.dAphi,
                             self.B, self.dBtheta, self.dBphi, self.U)
        
        covar_diff = np.max(np.abs(FIM_Rx - FIM_W))
        print(f"W vs Rx input equivalence: {'✓' if covar_diff < 1e-12 else '✗'} (max diff: {covar_diff:.2e})")
        
        # Test scaling properties
        FIM_2L = calculate_fim(2*self.L, self.noise_s, self.W, self.A, self.dAtheta, self.dAphi,
                              self.B, self.dBtheta, self.dBphi, self.U)
        scale_L_error = np.max(np.abs(FIM_2L - 2*FIM_W))
        print(f"L scaling property: {'✓' if scale_L_error < 1e-12 else '✗'} (error: {scale_L_error:.2e})")
        
        FIM_2noise = calculate_fim(self.L, 2*self.noise_s, self.W, self.A, self.dAtheta, self.dAphi,
                                  self.B, self.dBtheta, self.dBphi, self.U)
        scale_noise_error = np.max(np.abs(FIM_2noise - 0.5*FIM_W))
        print(f"Noise scaling property: {'✓' if scale_noise_error < 1e-12 else '✗'} (error: {scale_noise_error:.2e})")


def main():
    """Run the complete validation suite."""
    print("=== PYTHON calculateFIM VALIDATION AGAINST MATLAB REFERENCE ===\n")
    
    try:
        # Initialize validator
        validator = MATLABReferenceValidator()
        
        # Run validation
        passed, results = validator.validate_python_implementation()
        
        # Test input variations
        validator.test_input_variations()
        
        # Final summary
        print(f"\n=== VALIDATION SUMMARY ===")
        if passed:
            print("🎉 VALIDATION PASSED: Python implementation matches MATLAB reference!")
            print(f"   Maximum difference: {results['max_abs_diff']:.2e} (machine precision level)")
        else:
            print("❌ VALIDATION FAILED: Python implementation differs from MATLAB reference")
            print(f"   Maximum difference: {results['max_abs_diff']:.2e}")
            
        print(f"   Python computation time: {results['python_time']:.6f}s")
        print(f"   MATLAB computation time: {results['matlab_time']:.6f}s")
        print(f"   Speed ratio: {results['matlab_time']/results['python_time']:.2f}x")
        
        return passed
        
    except Exception as e:
        print(f"❌ Validation failed with error: {e}")
        return False


if __name__ == "__main__":
    success = main()
    sys.exit(0 if success else 1) 